{% set name = "opendrift" %}
{% set version = "1.14.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opendrift-{{ version }}.tar.gz
  sha256: bd6d302220c0f4ff369a7f8df8cbf8079869367e9d5278b0f323101392f6e2a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hodograph = opendrift.scripts.hodograph:main
    - readerinfo = opendrift.scripts.readerinfo:main
    - opendrift_plot = opendrift.scripts.opendrift_plot:main
    - opendrift_animate = opendrift.scripts.opendrift_animate:main
    - opendrift_gui = opendrift.scripts.opendrift_gui:main


requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - cartopy >=0.20
    - cmocean >=3.1.3
    - coloredlogs >=15.0.1,<16.0.0
    - geojson >=2.5.0
    - geopandas >=0.14
    - matplotlib-base >=3.5
    - nc-time-axis >=1.4.1,<2.0.0
    - netcdf4 >=1.6.1
    - numpy >=1.23
    - pynucos >=3
    - pyproj >=2.3
    - requests >=2.28.1,<3.0.0
    - roaring-landmask >=0.7.0
    - scipy >=1.9
    - utm >=0.7.0,<0.8.0
    - xarray >=2022.6.0
    - dask-core >=2022.9.0
    - gdal >=3.3.1,<4.0.0
    - pykdtree
    - xhistogram >=0.3
    - trajan >=0.6
    - adios_db >1.2
    - copernicusmarine >=2.0
    - bottleneck

test:
  imports:
    - opendrift
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/opendrift/
  summary: OpenDrift - a framework for ocean trajectory modeling
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauteh
    - knutfrode
