{% set name = "opendrift" %}
{% set version = "1.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opendrift-{{ version }}.tar.gz
  sha256: 42cd6082c09ab319ad61c142e3872a466270696bcc9d7b8fb7054a2d5e53d21e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hodograph = opendrift.scripts.hodograph:main
    - readerinfo = opendrift.scripts.readerinfo:main
    - opendrift_plot = opendrift.scripts.opendrift_plot:main
    - opendrift_animate = opendrift.scripts.opendrift_animate:main
    - opendrift_gui = opendrift.scripts.opendrift_gui:main


requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - poetry
  run:
    - python >=3.8,<3.12
    - cartopy >=0.20
    - cmocean >=2.0,<3.0
    - coloredlogs >=15.0.1,<16.0.0
    - geojson >=2.5.0,<3.0.0
    - matplotlib-base >=3.5
    - nc-time-axis >=1.4.1,<2.0.0
    - netcdf4 >=1.6
    - numpy >=1.23
    - pynucos >=3
    - pyproj >=2.3
    - requests >=2.28.1,<3.0.0
    - roaring-landmask >=0.7.0
    - scipy >=1.9
    - utm >=0.7.0,<0.8.0
    - xarray >=2022.6.0
    - dask-core >=2022.9.0
    - gdal >=3.3.1,<4.0.0
    - pykdtree
    - xhistogram >=0.3
    - trajan >=0.1
    - adios_db >=1.1

test:
  imports:
    - opendrift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/opendrift/
  summary: OpenDrift - a framework for ocean trajectory modeling
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauteh
    - knutfrode
